apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grade-submission-api
  template:
    metadata:
      labels:
        app: grade-submission-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: grade-submission-api
          image: ghcr.io//berrouyne/kubernetes-cicd-tutorial@sha256:7b068ceb86e2368244731c7a03ac29a3bab7f95670e5c376e6c9e3af9b068db8
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: grade-submission-api
  namespace: default
spec:
  selector:
    app: grade-submission-api
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
